import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { AuthProvider } from "../components/AuthContext";
import { LanguageProvider, type Language } from "../components/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Cookie에서 언어 읽기 (서버 사이드)
  const cookieStore = await cookies();
  const langCookie = cookieStore.get("lang")?.value;
  const lang = (langCookie === "ko" || langCookie === "en" || langCookie === "vi"
    ? langCookie
    : "ko") as Language;

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <LanguageProvider initialLanguage={lang}>
            {children}
          </LanguageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
